### ISSUE TITLE
'Copy' task needed when installing this as a dependency

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/scss#2]
@ashleynolan @nicbell @jpdriver and anyone else that might be interested.

The aim for this repo is to replace the `scss` directory in the main kickoff repo. I want this to be installed as an npm dependency when anyone clones kickoff or uses the generator. It is part of a larger effort to allow the sass framework to be used on other types of projects, for example in create-kickoff-app and beyond.

In order for this to be as seamless as possible, we need to create a `postinstall` script that, when run, copies the `scss` from `node_modules` into the Kickoff assets directory, or any other directory based on your project.

If it is a 'Kickoff' project, we can be fairly certain what the destination directory is going to be, but we can't be certain for other projects. It is for this reason, that I think we will need to have some config somewhere, like the `package.json` that people can use to define the destination.

If it is a 'Kickoff' project again, we can call this postinstall script automatically, but others may not be able to run it automatically because they may not have added the above config in `package.json`. For this reason, I think we should setup a simple `bin` file that is included with `scss` that references the config var (destination directory) and run the copy script.

What do you think?

P.S. I have not updated this package with the latest from the main repo, but will soon. 😄

**Comment by ashleynolan** [comment]
Couple of questions just off the top of my head:

1.  How do we do the copy?  Is it just a bash command in the package.json or were you thinking a gulp task?
2.  If this is a versioned package, how would versions be copied over when updated?  Or are we only thinking this would work on first install.
3. Once copied, would the copied SCSS then be checked in as part of the new project?

Sure there are other things to consider but these are the first things I could think of 🎱

**Comment by mrmartineau** [comment]
@ashleynolan answers below:

1. Copy task would be a bash script - definitely not something tied to the usual build tooling
2. It is a versioned package but I think, at least for the moment, that this would only apply to first install because of the way Kickoff is used by devs.
3. Yes, this is the plan.

Does it make more sense now? Is this a good idea? More questions appreciated.

**Comment by ashleynolan** [comment]
@mrmartineau Yep – makes more sense now.  I think point 2 is the only part I think would be tricky but if we see this as a single copy once installed, will likely be much easier.

I guess the only other thing that we would need to check is that if the folder already exists (has been checked in by one user) and another user clones the repo and does an install, it does a check to make sure it won’t overwrite the files that are already there.

Think it’ll work well otherwise though.

**Comment by mrmartineau** [comment]
> I guess the only other thing that we would need to check is that if the folder already exists

Good point, I hadn't thought of that :)
